// <auto-generated />
namespace DanceCompetitionApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dancers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dancers));
        
        string IMigrationMetadata.Id
        {
            get { return "202402011223324_dancers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
